In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import joblib
import os

plt.style.use('fivethirtyeight')

In [2]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.rand(3) * 1e-4 # small random weights
        self.eta = eta
        self.epochs = epochs

    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)

    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch + 1}")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
            
            
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)

## OR Operation

In [3]:
OR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,1]
}

df_or = pd.DataFrame(OR)
df_or

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [4]:
def prepare_data(df, target_col="y"):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    
    return X, y

X, y = prepare_data(df_or)

In [6]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [7]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [8]:
model_or = Perceptron(eta=0.1, epochs=10)
model_or.fit(X,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 1 1]
error: 
0    0
1    1
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 8.15066499e-05  1.00021118e-01 -9.99407256e-02]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[8.15066499e-05 1.00021118e-01 5.92743664e-05]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[8.15066499e-05 1.00021118e-01 5.92743664e-05]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    

In [9]:
model_or.predict(X=[[0,0]])

array([0])

## AND Operation

In [10]:
AND = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,0,0,1]
}

df_AND = pd.DataFrame(AND)

df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [11]:
X, y = prepare_data(df_AND)

ETA = 0.1
EPOCHS = 10

model_and = Perceptron(eta=ETA, epochs=EPOCHS)

model_and.fit(X, y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[5.06621536e-05 3.83021357e-05 6.67542508e-05]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[5.06621536e-05 3.83021357e-05 6.67542508e-05]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[5.06621536e-05 3.83021357e-05 6.67542508e-05]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[0 0 0 1]
error: 
0    0
1    0
2

In [12]:
model_and.predict(X=[[0,0]])

array([0])

## XOR Operation

In [13]:
XOR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,0]
}

df_XOR = pd.DataFrame(XOR)

df_XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [14]:
X, y = prepare_data(df_XOR)

ETA = 0.1
EPOCHS = 10

model_xor = Perceptron(eta=ETA, epochs=EPOCHS)

model_xor.fit(X, y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[-0.0999137  -0.09991494  0.10004741]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 8.62970024e-05  8.50636535e-05 -9.99525908e-02]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[-0.0999137  -0.09991494  0.10004741]
####################
--------------------
for epoch >> 4
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Na

In [15]:
model_xor.predict(X=[[0,0]])

array([1])